/*
 * Copyright (c) 2018-2020 by Kurt Duncan - All Rights Reserved
 */

package com.kadware.komodo.binaries.sandbox;

public class IntHandlers {

    public static final String[] SOURCE = {
        ". INTHANDLERS",
        ". Copyright (C) 2019-2020 by Kurt Duncan - All Rights Reserved",
        ".",
        "          $EXTEND",
        "          $INFO 1 3",
        "          $INFO 10 1",
        "",
        "$(0)",
        "          $LIT",
        "",
        "$(1)      . Interrupt handlers",
        "IH_00*    . Interrupt 0:Reserved - Hardware Default",
        "          HALT 01000",
        "",
        "IH_01*    . Interrupt 1:Hardware Check",
        "          HALT 01001",
        "",
        "IH_02*    . Interrupt 2:Diagnostic",
        "          HALT 01002",
        "",
        "IH_03*    . Interrupt 3:Reserved",
        "          HALT 01003",
        "",
        "IH_04*    . Interrupt 4:Reserved",
        "          HALT 01004",
        "",
        "IH_05*    . Interrupt 5:Reserved",
        "          HALT 01005",
        "",
        "IH_06*    . Interrupt 6:Reserved",
        "          HALT 01006",
        "",
        "IH_07*    . Interrupt 7:Reserved",
        "          HALT 01007",
        "",
        "IH_10*    . Interrupt 8:Reference Violation",
        "          HALT 01010",
        "",
        "IH_11*    . Interrupt 9:Addressing Exception",
        "          HALT 01011",
        "",
        "IH_12*    . Interrupt 10 Terminal Addressing Exception",
        "          HALT 01012",
        "",
        "IH_13*    . Interrupt 11 RCS/Generic Stack Under/Overflow",
        "          HALT 01013",
        "",
        "IH_14*    . Interrupt 12 Signal",
        "          HALT 01014",
        "",
        "IH_15*    . Interrupt 13 Test & Set",
        "          HALT 01015",
        "",
        "IH_16*    . Interrupt 14 Invalid Instruction",
        "          HALT 01016",
        "",
        "IH_17*    . Interrupt 15 Page Exception",
        "          HALT 01017",
        "",
        "IH_20*    . Interrupt 16 Arithmetic Exception",
        "          HALT 01020",
        "",
        "IH_21*    . Interrupt 17 Data Exception",
        "          HALT 01021",
        "",
        "IH_22*    . Interrupt 18 Operation Trap",
        "          HALT 01022",
        "",
        "IH_23*    . Interrupt 19 Breakpoint",
        "          HALT 01023",
        "",
        "IH_24*    . Interrupt 20 Quantum Timer",
        "          HALT 01024",
        "",
        "IH_25*    . Interrupt 21 Reserved",
        "          HALT 01025",
        "",
        "IH_26*    . Interrupt 22 Reserved",
        "          HALT 01026",
        "",
        "IH_27*    . Interrupt 23 Page(s) Zeroed",
        "          HALT 01027",
        "",
        "IH_30*    . Interrupt 24 Software Break",
        "          HALT 01030",
        "",
        "IH_31*    . Interrupt 25 Jump History Full",
        "          HALT 01031",
        "",
        "IH_32*    . Interrupt 26 Reserved",
        "          HALT 01032",
        "",
        "IH_33*    . Interrupt 27 Dayclock",
        "          HALT 01033",
        "",
        "IH_34*    . Interrupt 28 Performance Monitoring",
        "          HALT 01034",
        "",
        "IH_35*    . Interrupt 29 Initial Program Load (IPL)",
        "          . Default action is to simply return from the interrupt.",
        "          . This happens every time the IP is started via start().",
        "          UR        *0,EX1,B26-16 . should be 0,EX1,B26 but assembler is broken",//TODO fix this after fixing minalib
        "",
        "IH_36*    . UPI Initial",
        "          HALT 01036",
        "",
        "IH_37*    . UPI Normal",
        "          HALT 01037",
    };
}
