/*
 * Copyright (c) 2019 by Kurt Duncan - All Rights Reserved
 */

package com.kadware.komodo.kos;

public class IntHandlers {

    public static final String[] SOURCE = {
        ". INTHANDLERS",
        ". Copyright (C) 2019 by Kurt Duncan - All Rights Reserved",
        ".",
        ". This code contains the interrupt handlers",
        ".",
        "$(1)      $LIT",
        ".",
        "IH$01*    IAR       0401 . hardware check",
        "IH$00* .",
        "IH$02* .",
        "IH$03* .",
        "IH$04* .",
        "IH$05* .",
        "IH$06* .",
        "IH$07* .",
        "IH$10* .",
        "IH$11* .",
        "IH$12* .",
        "IH$13* .",
        "IH$14* .",
        "IH$15* .",
        "IH$16* .",
        "IH$17* .",
        "IH$20* .",
        "IH$21* .",
        "IH$22* .",
        "IH$23* .",
        "IH$24* .",
        "IH$25* .",
        "IH$26* .",
        "IH$27* .",
        "IH$30* .",
        "IH$31* .",
        "IH$32* .",
        "IH$33* .",
        "IH$34* .",
        "IH$35* .",
        "IH$36* .",
        "IH$37* .",
        "IH$40* .",
        "IH$41* .",
        "IH$42* .",
        "IH$43* .",
        "IH$44* .",
        "IH$45* .",
        "IH$46* .",
        "IH$47* .",
        "IH$50* .",
        "IH$51* .",
        "IH$52* .",
        "IH$53* .",
        "IH$54* .",
        "IH$55* .",
        "IH$56* .",
        "IH$57* .",
        "IH$60* .",
        "IH$61* .",
        "IH$62* .",
        "IH$63* .",
        "IH$64* .",
        "IH$65* .",
        "IH$66* .",
        "IH$67* .",
        "IH$70* .",
        "IH$71* .",
        "IH$72* .",
        "IH$73* .",
        "IH$74* .",
        "IH$75* .",
        "IH$76* .",
        "IH$77* .",
        "          IAR       0400 . Undefined interrupt",
    };
}
